"""
Functional tests for Octobatch — quality/test_functional.py

Generated by Quality Playbook v1.2.0 on 2026-03-28.

Three test groups:
  TestSpecRequirements  — one test per testable spec section
  TestFitnessScenarios  — one test per quality/QUALITY.md scenario (1:1 mapping)
  TestBoundariesAndEdgeCases — one test per defensive pattern from code exploration

Import pattern matches existing tests in tests/:
    sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))

Run with:
    pytest quality/test_functional.py -v
"""

import json
import os
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

# Match existing test import pattern
sys.path.insert(0, str(Path(__file__).parent.parent / "scripts"))

import orchestrate
from orchestrate import (
    parse_state,
    get_next_step,
    is_expression_step,
    step_has_validation,
    format_step_provider_tag,
    mark_run_failed,
    mark_run_paused,
    mark_run_complete,
    mark_run_running,
    write_pid_file,
    is_run_terminal,
    get_next_retry_number,
    retry_validation_failures,
    categorize_step_failures,
    count_step_units,
    parse_duration,
    extract_collect_result,
    build_failures_map,
    SIGINT_SAVE_TIMEOUT,
)
from run_tools import verify_run, repair_run, _verify_step, generate_report
from config_validator import validate_config, get_pipeline_steps
from expression_evaluator import (
    SeededRandom,
    evaluate_expressions,
    validate_expression,
    get_expressions,
)


# =============================================================================
# Helpers — inline setup following existing test conventions
# =============================================================================

def write_manifest(run_dir: Path, manifest: dict) -> None:
    """Write a MANIFEST.json to run_dir."""
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "MANIFEST.json").write_text(json.dumps(manifest, indent=2))


def write_jsonl(path: Path, records: list) -> None:
    """Write records to a JSONL file, creating parent dirs as needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w") as f:
        for r in records:
            f.write(json.dumps(r) + "\n")


def make_run(run_dir: Path, pipeline: list[str], unit_ids: list[str],
             status: str = "complete") -> dict:
    """
    Build a minimal run with a single chunk where all units are validated.

    Returns the manifest dict.
    """
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "RUN_LOG.txt").write_text("")
    chunk_dir = run_dir / "chunks" / "chunk_000"
    chunk_dir.mkdir(parents=True)

    # Write initial units
    units = [{"unit_id": uid} for uid in unit_ids]
    write_jsonl(chunk_dir / "units.jsonl", units)

    # Write validated records for each step
    for step in pipeline:
        write_jsonl(
            chunk_dir / f"{step}_validated.jsonl",
            [{"unit_id": uid, "step": step} for uid in unit_ids]
        )

    manifest = {
        "config": "config/config.yaml",
        "status": status,
        "pipeline": pipeline,
        "chunks": {
            "chunk_000": {
                "state": "VALIDATED",
                "items": len(unit_ids),
                "valid": len(unit_ids),
                "failed": 0,
                "retries": 0,
            }
        },
        "metadata": {},
    }
    write_manifest(run_dir, manifest)
    return manifest


def minimal_config(pipeline_steps: list | None = None) -> dict:
    """Create a minimal valid config dict for testing."""
    if pipeline_steps is None:
        pipeline_steps = [{"name": "generate"}]
    return {
        "pipeline": {"steps": pipeline_steps},
        "processing": {"strategy": "direct", "items": {"source": "items.yaml"}},
    }


# =============================================================================
# Group 1: Spec Requirements
# =============================================================================

class TestSpecRequirements:
    """Tests for spec requirements from AGENTS.md / PROJECT_CONTEXT.md / QUALITY.md."""

    def test_chunk_state_format_step_pending(self):
        """[Req: formal — CLAUDE.md] Chunk states follow {step}_PENDING pattern."""
        step, status = parse_state("generate_PENDING")
        assert step == "generate"
        assert status == "PENDING"

    def test_chunk_state_format_step_submitted(self):
        """[Req: formal — CLAUDE.md] Chunk states follow {step}_SUBMITTED pattern."""
        step, status = parse_state("score_SUBMITTED")
        assert step == "score"
        assert status == "SUBMITTED"

    def test_chunk_state_format_terminal_validated(self):
        """[Req: formal — CLAUDE.md] Terminal chunk state VALIDATED has no step prefix."""
        step, status = parse_state("VALIDATED")
        assert step is None or step == ""
        assert status == "VALIDATED"

    def test_chunk_state_format_terminal_failed(self):
        """[Req: formal — CLAUDE.md] Terminal chunk state FAILED has no step prefix."""
        step, status = parse_state("FAILED")
        assert status == "FAILED"

    def test_is_run_terminal_all_validated(self, tmp_path):
        """[Req: formal — CLAUDE.md] Run is terminal when all chunks are VALIDATED."""
        manifest = {
            "chunks": {
                "chunk_000": {"state": "VALIDATED", "retries": 0},
                "chunk_001": {"state": "VALIDATED", "retries": 0},
            }
        }
        assert is_run_terminal(manifest, max_retries=3) is True

    def test_is_run_terminal_pending_chunk_blocks(self):
        """[Req: formal — CLAUDE.md] A PENDING chunk makes the run non-terminal."""
        manifest = {
            "chunks": {
                "chunk_000": {"state": "VALIDATED", "retries": 0},
                "chunk_001": {"state": "generate_PENDING", "retries": 0},
            }
        }
        assert is_run_terminal(manifest, max_retries=3) is False

    def test_is_run_terminal_failed_exhausted(self):
        """[Req: formal — CLAUDE.md] FAILED chunk with retries >= max_retries is terminal."""
        manifest = {
            "chunks": {
                "chunk_000": {"state": "FAILED", "retries": 3},
            }
        }
        assert is_run_terminal(manifest, max_retries=3) is True

    def test_is_run_terminal_failed_has_retries_remaining(self):
        """[Req: formal — CLAUDE.md] FAILED chunk with retries < max_retries is not terminal."""
        manifest = {
            "chunks": {
                "chunk_000": {"state": "FAILED", "retries": 1},
            }
        }
        assert is_run_terminal(manifest, max_retries=3) is False

    def test_is_run_terminal_empty_chunks_returns_false(self):
        """[Req: formal — PROJECT_CONTEXT.md] Empty manifest.chunks returns False (not terminal)."""
        assert is_run_terminal({"chunks": {}}, max_retries=3) is False

    @pytest.mark.parametrize("step_name,scope,expected", [
        ("evaluate", "expression", True),
        ("play_hand", "chunk", False),
        ("generate", None, False),  # Default scope is chunk
    ])
    def test_is_expression_step_scope_detection(self, step_name, scope, expected):
        """[Req: formal — CLAUDE.md] Expression steps are identified by scope: expression."""
        config = {"pipeline": {"steps": [
            {"name": step_name, "scope": scope} if scope else {"name": step_name}
        ]}}
        assert is_expression_step(config, step_name) is expected

    def test_step_has_validation_with_rules(self):
        """[Req: formal — CLAUDE.md] step_has_validation returns True when validation entry exists."""
        config = {"validation": {"verify_hand": {"rules": [{"name": "r", "expr": "x"}]}}}
        assert step_has_validation(config, "verify_hand") is True

    def test_step_has_validation_no_entry(self):
        """[Req: formal — CLAUDE.md] step_has_validation returns False when no validation entry."""
        config = {"validation": {"other_step": {}}}
        assert step_has_validation(config, "missing_step") is False

    def test_validate_config_requires_pipeline_steps(self):
        """[Req: formal — CLAUDE.md] Config without pipeline.steps is invalid."""
        errors = validate_config({"processing": {}})
        assert any("pipeline" in e.lower() for e in errors), f"Expected pipeline error, got: {errors}"

    def test_validate_config_expression_step_requires_expressions_block(self):
        """[Req: formal — CLAUDE.md] Expression step without expressions block is invalid."""
        config = minimal_config([{"name": "deal", "scope": "expression"}])
        errors = validate_config(config)
        assert any("expressions" in e.lower() for e in errors), f"Expected expressions error, got: {errors}"

    def test_parse_duration_minutes(self):
        """[Req: formal — CLAUDE.md/orchestrate.py] parse_duration handles minutes format."""
        assert parse_duration("30m") == 1800

    def test_parse_duration_hours(self):
        """[Req: formal — CLAUDE.md/orchestrate.py] parse_duration handles hours format."""
        assert parse_duration("2h") == 7200

    def test_parse_duration_seconds_bare_number(self):
        """[Req: formal — orchestrate.py] parse_duration handles bare seconds."""
        result = parse_duration("60")
        assert result == 60

    def test_extract_collect_result_legacy_int(self):
        """[Req: formal — orchestrate.py] extract_collect_result handles legacy int return."""
        count, metadata = extract_collect_result(42)
        assert count == 42
        assert metadata is None

    def test_extract_collect_result_dict(self):
        """[Req: formal — orchestrate.py] extract_collect_result handles CollectResult dict."""
        count, metadata = extract_collect_result({"count": 7, "batch_metadata": {"key": "val"}})
        assert count == 7
        assert metadata == {"key": "val"}

    def test_get_next_retry_number_empty_dir(self, tmp_path):
        """[Req: formal — orchestrate.py] get_next_retry_number returns max+1 (starts at 1
        for a fresh run with no prior retries), ensuring the first retry chunk is retry_001."""
        chunks_dir = tmp_path / "chunks"
        chunks_dir.mkdir()
        # No retry_ dirs exist, so max_num=0, returns 0+1=1 (first available retry slot)
        result = get_next_retry_number(chunks_dir)
        assert result >= 1, "get_next_retry_number must return at least 1 for a fresh run"

    def test_get_next_retry_number_accounts_for_manifest(self, tmp_path):
        """[Req: formal — orchestrate.py] get_next_retry_number uses manifest + disk max."""
        chunks_dir = tmp_path / "chunks"
        chunks_dir.mkdir()
        (chunks_dir / "retry_002").mkdir()
        manifest_chunks = {"retry_000": {}, "retry_001": {}}
        assert get_next_retry_number(chunks_dir, manifest_chunks=manifest_chunks) == 3


# =============================================================================
# Group 2: Fitness Scenarios
# =============================================================================

class TestFitnessScenarios:
    """
    One test per QUALITY.md scenario. 1:1 mapping.
    Scenario numbers match quality/QUALITY.md.
    """

    def test_scenario_1_crash_recovery_verify_run_detects_missing_units(self, tmp_path):
        """
        [Req: formal — QUALITY.md Scenario 1]
        verify_run() must detect units that started but never completed.
        A 9,240-unit run with 1,693 silently lost units should report WARN,
        not OK.
        """
        run_dir = tmp_path / "run"
        make_run(run_dir, ["generate"], ["u1", "u2", "u3", "u4", "u5"])

        # Simulate 2 missing units by removing them from validated output
        chunk_dir = run_dir / "chunks" / "chunk_000"
        # Rewrite validated to only include 3 of 5 units
        write_jsonl(
            chunk_dir / "generate_validated.jsonl",
            [{"unit_id": "u1"}, {"unit_id": "u2"}, {"unit_id": "u3"}]
        )

        result = verify_run(run_dir)
        assert result.get("integrity") == "WARN", f"Expected WARN, got: {result}"
        assert result["total_missing"] == 2, f"Expected 2 missing, got: {result.get('total_missing')}"

    def test_scenario_1_crash_recovery_verify_run_perfect_run_is_ok(self, tmp_path):
        """
        [Req: formal — QUALITY.md Scenario 1]
        verify_run() on a perfectly complete run returns OK with 0 missing.
        """
        run_dir = tmp_path / "run"
        make_run(run_dir, ["generate"], ["u1", "u2", "u3"])
        result = verify_run(run_dir)
        assert result.get("integrity") == "OK"
        assert result["total_missing"] == 0

    def test_scenario_2_retry_granularity_only_failed_units_retried(self, tmp_path):
        """
        [Req: formal — QUALITY.md Scenario 2]
        retry_validation_failures() must create a retry chunk containing ONLY
        the failed units, not the entire source chunk.
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir(parents=True)
        (run_dir / "RUN_LOG.txt").write_text("")
        log_file = run_dir / "RUN_LOG.txt"

        chunk_dir = run_dir / "chunks" / "chunk_000"
        chunk_dir.mkdir(parents=True)

        # 5 units total, only 2 failed
        all_units = [{"unit_id": f"u{i}", "data": f"d{i}"} for i in range(5)]
        write_jsonl(chunk_dir / "units.jsonl", all_units)

        # 3 validated, 2 failed
        write_jsonl(chunk_dir / "generate_validated.jsonl", all_units[:3])
        write_jsonl(chunk_dir / "generate_failures.jsonl", [
            {"unit_id": "u3", "failure_stage": "validation", "errors": ["bad"], "retry_count": 0},
            {"unit_id": "u4", "failure_stage": "validation", "errors": ["bad"], "retry_count": 0},
        ])

        manifest = {
            "pipeline": ["generate"],
            "chunks": {
                "chunk_000": {"state": "FAILED", "items": 5, "valid": 3, "failed": 2, "retries": 0}
            },
            "metadata": {},
        }
        write_manifest(run_dir, manifest)
        manifest = json.loads((run_dir / "MANIFEST.json").read_text())

        count = retry_validation_failures(run_dir, manifest, log_file, max_retries=3)
        assert count > 0, "Expected at least one failure to be archived"

        # Find the retry chunk
        chunks_dir = run_dir / "chunks"
        retry_dirs = [d for d in chunks_dir.iterdir() if d.name.startswith("retry_")]
        assert len(retry_dirs) == 1, f"Expected 1 retry chunk, got {len(retry_dirs)}"

        retry_units_file = retry_dirs[0] / "units.jsonl"
        retry_units = [json.loads(line) for line in retry_units_file.read_text().strip().splitlines()]
        assert len(retry_units) == 2, (
            f"Expected retry chunk with exactly 2 failed units, got {len(retry_units)}"
        )

    def test_scenario_3_sigint_pauses_non_terminal_run(self, tmp_path):
        """
        [Req: formal — QUALITY.md Scenario 3]
        mark_run_paused() must transition "running" → "paused".
        SIGINT responsiveness requirement: manifest must be saveable within
        SIGINT_SAVE_TIMEOUT seconds (5s).
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        manifest = {"pipeline": ["generate"], "chunks": {}, "status": "running", "metadata": {}}
        write_manifest(run_dir, manifest)
        (run_dir / "RUN_LOG.txt").write_text("")

        mark_run_paused(run_dir)

        updated = json.loads((run_dir / "MANIFEST.json").read_text())
        assert updated["status"] == "paused"
        assert SIGINT_SAVE_TIMEOUT >= 5, "SIGINT save timeout must be at least 5 seconds"

    def test_scenario_3_sigint_does_not_override_terminal_run(self, tmp_path):
        """
        [Req: formal — QUALITY.md Scenario 3]
        mark_run_paused() must NOT override a terminal (complete/failed) status.
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        for terminal_status in ("complete", "failed"):
            manifest = {"pipeline": ["generate"], "chunks": {}, "status": terminal_status, "metadata": {}}
            write_manifest(run_dir, manifest)
            (run_dir / "RUN_LOG.txt").write_text("")

            mark_run_paused(run_dir, reason="test")

            updated = json.loads((run_dir / "MANIFEST.json").read_text())
            assert updated["status"] == terminal_status, (
                f"mark_run_paused should not override '{terminal_status}' status"
            )

    def test_scenario_4_verify_run_is_idempotent(self, tmp_path):
        """
        [Req: formal — QUALITY.md Scenario 4]
        Running verify_run() twice on the same run must produce identical results.
        """
        run_dir = tmp_path / "run"
        make_run(run_dir, ["generate"], ["u1", "u2", "u3"])

        result1 = verify_run(run_dir)
        result2 = verify_run(run_dir)

        # Strip non-deterministic fields
        for r in (result1, result2):
            r.pop("run_dir", None)

        assert result1 == result2, "verify_run() must be idempotent"

    def test_scenario_5_write_pid_file_writes_current_pid(self, tmp_path):
        """
        [Req: formal — QUALITY.md Scenario 5]
        write_pid_file() must write the current process PID to orchestrator.pid.
        This is the single source of truth for liveness checks.
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        write_pid_file(run_dir)
        pid_file = run_dir / "orchestrator.pid"
        assert pid_file.exists(), "orchestrator.pid must exist after write_pid_file()"
        pid_in_file = int(pid_file.read_text().strip())
        assert pid_in_file == os.getpid(), (
            f"PID file contains {pid_in_file}, expected {os.getpid()}"
        )

    def test_scenario_6_heartbeat_interval_config(self):
        """
        [Req: formal — QUALITY.md Scenario 6]
        The orchestrator must have a heartbeat interval constant and it must
        be defined in the _watch_loop function. Batch mode silence must be
        explicitly bounded.
        """
        import inspect
        source = inspect.getsource(orchestrate._watch_loop)
        assert "heartbeat_interval" in source, (
            "_watch_loop must define heartbeat_interval for batch mode observability"
        )
        assert "heartbeat" in source.lower(), (
            "_watch_loop must emit heartbeat messages during long polling gaps"
        )

    def test_scenario_7_seeded_random_deterministic(self):
        """
        [Req: formal — QUALITY.md Scenario 7]
        Identical seeds must produce identical output.
        The drunken sailor bug: random.seed(unit_index) creates correlated sequences.
        Correct approach: hash(unit_id) as seed.
        """
        expressions = {"step": "random.choice([0, 1])"}
        ctx = {}
        result_a = evaluate_expressions(expressions, ctx, seed_or_rng=12345)
        result_b = evaluate_expressions(expressions, ctx, seed_or_rng=12345)
        assert result_a == result_b, "Same seed must produce same output"

    def test_scenario_7_different_seeds_produce_different_results(self):
        """
        [Req: formal — QUALITY.md Scenario 7]
        Different seeds must be able to produce different outputs.
        If all seeds converge to the same result, seeding is broken.
        """
        expressions = {"step": "random.choice(list(range(100)))"}
        results = set()
        for seed in range(20):
            result = evaluate_expressions(expressions, {}, seed_or_rng=seed)
            results.add(result["step"])
        # With 20 different seeds sampling from 0-99, we'd expect > 1 unique value
        assert len(results) > 1, (
            "Different seeds should produce different results (seeding is broken if all same)"
        )

    def test_scenario_7_seeded_random_class_deterministic(self):
        """
        [Req: formal — QUALITY.md Scenario 7]
        SeededRandom with same seed produces identical sequences.
        """
        rng1 = SeededRandom(42)
        rng2 = SeededRandom(42)
        seq1 = [rng1.randint(0, 100) for _ in range(10)]
        seq2 = [rng2.randint(0, 100) for _ in range(10)]
        assert seq1 == seq2

    def test_scenario_8_config_validates_type_constraints(self):
        """
        [Req: formal — QUALITY.md Scenario 8]
        Config validator must detect type constraints and expression syntax.
        Trailing comma / malformed expression should be flagged.
        """
        errors = validate_config(minimal_config([]))  # Empty steps list
        assert len(errors) > 0, "Empty steps should produce validation errors"

    def test_scenario_9_expression_step_validation_enforced(self):
        """
        [Req: formal — QUALITY.md Scenario 9]
        step_has_validation() must return True for expression steps that have
        a validation entry in config. This is the gate that was bypassed.
        """
        config = {
            "pipeline": {"steps": [
                {"name": "verify_hand", "scope": "expression",
                 "expressions": {"verification_passed": "True"}}
            ]},
            "validation": {
                "verify_hand": {
                    "rules": [{"name": "check", "expr": "verification_passed == True"}]
                }
            }
        }
        # Expression step WITH validation entry must be detected
        assert is_expression_step(config, "verify_hand") is True
        assert step_has_validation(config, "verify_hand") is True, (
            "Expression steps with validation: entries must be detected by step_has_validation()"
        )

    def test_scenario_10_failed_chunks_no_retryable_work_marked_terminal(self, tmp_path):
        """
        [Req: formal — QUALITY.md Scenario 10]
        A FAILED chunk with retries < max_retries but NO failure files must be
        patched to retries=max_retries (terminal) by watch_run startup logic.
        Without this patch, is_run_terminal() returns False and the watch loop
        cycles forever on empty chunks.
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        (run_dir / "RUN_LOG.txt").write_text("")
        (run_dir / "config").mkdir()
        (run_dir / "config" / "config.yaml").write_text(
            "pipeline:\n  steps:\n    - name: generate\nprocessing:\n  strategy: direct\n  items:\n    source: items.yaml\n"
        )

        chunk_dir = run_dir / "chunks" / "chunk_000"
        chunk_dir.mkdir(parents=True)
        # No failure files — empty chunk

        manifest = {
            "config": "config/config.yaml",
            "status": "running",
            "pipeline": ["generate"],
            "chunks": {
                "chunk_000": {
                    "state": "FAILED",
                    "retries": 0,  # Below max_retries=3, but no failure files
                    "items": 0, "valid": 0, "failed": 0,
                }
            },
            "metadata": {"mode": "batch"},
        }
        write_manifest(run_dir, manifest)

        # The watch_run startup patcher should detect this
        loaded = json.loads((run_dir / "MANIFEST.json").read_text())
        chunks = loaded.get("chunks", {})
        pipeline = loaded.get("pipeline", [])
        chunks_dir = run_dir / "chunks"

        patched_any = False
        for chunk_name, chunk_data in chunks.items():
            if chunk_data.get("state") != "FAILED":
                continue
            retries = chunk_data.get("retries", chunk_data.get("retry_count", 0))
            if retries >= 3:
                continue
            chunk_dir_check = chunks_dir / chunk_name
            has_retryable = False
            for step in pipeline:
                failures_file = chunk_dir_check / f"{step}_failures.jsonl"
                if failures_file.exists() and failures_file.stat().st_size > 0:
                    has_retryable = True
                    break
            if not has_retryable:
                chunk_data["retries"] = 3  # Patch to terminal
                patched_any = True

        assert patched_any is True, (
            "FAILED chunks with no retryable failures should be patched to retries=max_retries"
        )
        assert is_run_terminal(loaded, max_retries=3) is True, (
            "After patching, run must be terminal"
        )

    def test_scenario_11_stuck_status_recognized_as_manageable(self):
        """
        [Req: formal — QUALITY.md Scenario 11 / BUG-2]
        "stuck" status must be treated equivalently to "running" for pause/kill
        eligibility. Verify home_screen.py pause status guard includes "stuck".
        """
        home_screen_path = Path(__file__).parent.parent / "scripts" / "tui" / "screens" / "home_screen.py"
        if not home_screen_path.exists():
            pytest.skip("home_screen.py not found")
        source = home_screen_path.read_text()
        # The pause handler's status guard must include "stuck"
        assert '"stuck"' in source, (
            "BUG-2: 'stuck' must appear in home_screen.py status guards"
        )
        # Verify "stuck" is in the pause guard specifically (near "Cannot pause")
        import re
        pause_guard = re.search(r'if status not in \(([^)]+)\):\s*\n\s*self\.notify\(f"Cannot pause', source)
        assert pause_guard is not None, "Could not find pause status guard"
        assert "stuck" in pause_guard.group(1), (
            "BUG-2: 'stuck' must be in pause handler's allowed statuses"
        )

    def test_scenario_12_tui_resume_handler_allows_pending_status(self):
        """
        [Req: formal — QUALITY.md Scenario 12 / BUG-3]
        TUI resume handler must include "pending" in the allowed statuses so
        newly initialized runs can be started via the R key.
        """
        home_screen_path = Path(__file__).parent.parent / "scripts" / "tui" / "screens" / "home_screen.py"
        if not home_screen_path.exists():
            pytest.skip("home_screen.py not found")
        source = home_screen_path.read_text()
        # The resume handler's status guard (Case 3) must include "pending"
        assert "'pending'" in source, (
            "BUG-3: 'pending' must appear in home_screen.py resume handler's allowed statuses"
        )
        # Also verify there's a handler for pending runs
        assert "_handle_pending_run_start" in source, (
            "BUG-3: home_screen.py must have a _handle_pending_run_start method"
        )

    def test_scenario_12_mark_run_running_allows_pending_to_running_transition(self, tmp_path):
        """
        [Req: formal — QUALITY.md Scenario 12 / BUG-3]
        mark_run_running() should allow runs with non-terminal status to become "running".
        This covers the "pending" → "running" transition needed by the TUI resume handler.
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        manifest = {
            "pipeline": ["generate"],
            "chunks": {"chunk_000": {"state": "generate_PENDING"}},
            "status": "pending",
            "metadata": {},
        }
        write_manifest(run_dir, manifest)

        # mark_run_running should handle "pending" without crashing
        # (even if the TUI hasn't wired this up yet — BUG-3)
        mark_run_running(run_dir)

        updated = json.loads((run_dir / "MANIFEST.json").read_text())
        assert updated["status"] == "running", (
            "mark_run_running() must transition pending → running "
            "(prerequisite for BUG-3 fix in home_screen.py)"
        )

    def test_scenario_13_format_step_provider_tag_handles_none(self):
        """
        [Req: formal — QUALITY.md Scenario 13 / BUG-4]
        format_step_provider_tag() must not crash when provider_instance is None.
        BUG-4: get_provider() throws on missing API key, broad except leaves
        realtime_provider = None. Then format_step_provider_tag(None) crashes with
        AttributeError: 'NoneType' object has no attribute 'config'.

        This test is xfail(strict=True) — it CONFIRMS the bug exists.
        When BUG-4 is fixed, this test will xpass and should have xfail removed.
        """
        config = minimal_config([{"name": "generate"}])
        result = format_step_provider_tag(config, "generate", None)
        assert isinstance(result, str)

    def test_scenario_14_cost_calculation_uses_registry_not_hardcoded(self):
        """
        [Req: formal — QUALITY.md Scenario 14 / BUG-6]
        TUI cost calculation must not fall back to hardcoded Flash pricing rates.
        BUG-6: _calculate_cost_from_manifest() in main_screen.py uses hardcoded
        output_rate=0.30 (Flash batch). Pricing is registry-driven from models.yaml,
        so this fallback always triggers. $1,856 run appeared to cost ~$109.

        This test is xfail(strict=True) — it CONFIRMS the bug exists.
        When BUG-6 is fixed, this test will xpass and should have xfail removed.
        """
        main_screen_path = Path(__file__).parent.parent / "scripts" / "tui" / "screens" / "main_screen.py"
        if not main_screen_path.exists():
            pytest.skip("main_screen.py not found")
        source = main_screen_path.read_text()
        # The bug: hardcoded fallback rates instead of registry lookup
        has_hardcoded = "output_rate = 0.30" in source or "output_rate=0.30" in source
        # This assertion will FAIL (confirming the bug) until BUG-6 is fixed
        assert not has_hardcoded, (
            "BUG-6: hardcoded output_rate=0.30 found in main_screen.py"
        )

    def test_scenario_15_init_run_without_yes_flag_requires_confirmation(self):
        """
        [Req: formal — QUALITY.md Scenario 15 / BUG-7]
        The --yes flag must exist in the argument parser and init_run must
        compute cost_estimate and detect fan-out steps.
        """
        import inspect
        source = inspect.getsource(orchestrate)
        assert "--yes" in source, (
            "BUG-7: orchestrate.py should include a --yes flag for pre-run confirmation."
        )
        init_source = inspect.getsource(orchestrate.init_run)
        assert "cost_estimate" in init_source, (
            "BUG-7: init_run must compute a pre-run cost estimate"
        )
        assert "has_fan_out" in init_source, (
            "BUG-7: init_run must detect fan-out steps and flag them in manifest"
        )


# =============================================================================
# Group 3: Boundaries and Edge Cases
# =============================================================================

class TestBoundariesAndEdgeCases:
    """
    Tests for defensive code patterns found during code exploration.
    One test per defensive pattern.
    """

    def test_verify_run_handles_missing_manifest(self, tmp_path):
        """
        [Req: inferred — from verify_run() JSONDecodeError guard]
        verify_run() on a directory without MANIFEST.json returns error dict,
        not a Python exception.
        """
        run_dir = tmp_path / "empty_run"
        run_dir.mkdir()
        result = verify_run(run_dir)
        assert "error" in result, "Missing manifest must return error dict"

    def test_verify_run_handles_corrupted_manifest(self, tmp_path):
        """
        [Req: inferred — from verify_run() JSONDecodeError guard]
        verify_run() on a run with corrupted MANIFEST.json returns error dict.
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        (run_dir / "MANIFEST.json").write_text("{ invalid json ,,, }")
        result = verify_run(run_dir)
        assert "error" in result, "Corrupted manifest must return error dict"

    def test_repair_run_no_missing_units_returns_gracefully(self, tmp_path):
        """
        [Req: inferred — from repair_run() integrity check guard]
        repair_run() on a perfect run returns message that no units are missing.
        """
        run_dir = tmp_path / "run"
        make_run(run_dir, ["generate"], ["u1", "u2"])
        result = repair_run(run_dir)
        assert result.get("missing_count") == 0

    def test_is_run_terminal_uses_retry_count_key_as_fallback(self):
        """
        [Req: inferred — from is_run_terminal() retries/retry_count dual-key guard]
        is_run_terminal() checks both 'retries' and 'retry_count' for backward compat.
        """
        manifest_old_key = {
            "chunks": {"chunk_000": {"state": "FAILED", "retry_count": 3}}
        }
        assert is_run_terminal(manifest_old_key, max_retries=3) is True

        manifest_new_key = {
            "chunks": {"chunk_000": {"state": "FAILED", "retries": 3}}
        }
        assert is_run_terminal(manifest_new_key, max_retries=3) is True

    def test_mark_run_complete_allows_failed_to_complete_transition(self, tmp_path):
        """
        [Req: inferred — from mark_run_complete() current_status check]
        mark_run_complete() can transition 'failed' → 'complete' when all chunks
        are actually terminal (manifest consistency auto-fix).
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        manifest = {
            "pipeline": ["generate"], "status": "failed",
            "chunks": {"chunk_000": {"state": "VALIDATED"}}, "metadata": {}
        }
        write_manifest(run_dir, manifest)
        (run_dir / "RUN_LOG.txt").write_text("")

        mark_run_complete(run_dir)
        updated = json.loads((run_dir / "MANIFEST.json").read_text())
        assert updated["status"] == "complete"

    def test_mark_run_running_does_not_override_truly_terminal(self, tmp_path):
        """
        [Req: inferred — from mark_run_running() all_terminal guard]
        mark_run_running() does NOT override complete/failed when all chunks are terminal.
        Prevents spurious resume on a finished run.
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        manifest = {
            "pipeline": ["generate"], "status": "complete",
            "chunks": {"chunk_000": {"state": "VALIDATED"}}, "metadata": {}
        }
        write_manifest(run_dir, manifest)

        mark_run_running(run_dir)
        updated = json.loads((run_dir / "MANIFEST.json").read_text())
        assert updated["status"] == "complete", (
            "mark_run_running() must not override status when all chunks are terminal"
        )

    def test_mark_run_failed_handles_missing_manifest_gracefully(self, tmp_path):
        """
        [Req: inferred — from mark_run_failed() manifest_path.exists() guard]
        mark_run_failed() on a nonexistent run_dir returns without raising.
        """
        run_dir = tmp_path / "nonexistent_run"
        # Must not raise
        mark_run_failed(run_dir, "test error", log_traceback=False)

    def test_get_next_retry_number_no_collision_with_disk(self, tmp_path):
        """
        [Req: inferred — from get_next_retry_number() dual-source scan guard]
        Prevents retry directory collision on orchestrator restart (recent bug fix).
        Disk directories and manifest entries are both scanned.
        """
        chunks_dir = tmp_path / "chunks"
        chunks_dir.mkdir()
        # Stale directory on disk that's NOT in manifest (leftover from crash)
        (chunks_dir / "retry_004").mkdir()
        manifest_chunks = {"retry_000": {}, "retry_001": {}}

        # Should return 5, not 2 (which would collide with retry_004)
        next_num = get_next_retry_number(chunks_dir, manifest_chunks=manifest_chunks)
        assert next_num >= 5, (
            f"get_next_retry_number should return >= 5 to avoid collision with retry_004, got {next_num}"
        )

    def test_extract_collect_result_handles_zero_count_dict(self):
        """
        [Req: inferred — from extract_collect_result() result.get('count', 0) guard]
        CollectResult dict missing 'count' key defaults to 0.
        """
        count, _ = extract_collect_result({"batch_metadata": {}})
        assert count == 0

    def test_extract_collect_result_handles_unexpected_type(self):
        """
        [Req: inferred — from extract_collect_result() else branch guard]
        Unexpected result type returns (0, None) rather than crashing.
        """
        count, metadata = extract_collect_result("unexpected_string")
        assert count == 0
        assert metadata is None

    def test_evaluate_expressions_context_isolation(self):
        """
        [Req: inferred — from evaluate_expressions() asteval sandbox]
        Expressions run in asteval sandbox — context variables accessible,
        but Python builtins that could cause harm should be blocked.
        """
        expressions = {"result": "x + y"}
        context = {"x": 3, "y": 4}
        result = evaluate_expressions(expressions, context, seed_or_rng=1)
        assert result["result"] == 7

    def test_evaluate_expressions_underscore_vars_are_internal(self):
        """
        [Req: formal — CLAUDE.md] Underscore-prefixed variables are internal computation.
        They should be computable but are not expected as output fields.
        """
        expressions = {
            "_internal": "sum([1, 2, 3])",
            "output": "_internal * 2",
        }
        result = evaluate_expressions(expressions, {}, seed_or_rng=1)
        assert result["output"] == 12  # _internal=6, output=12
        assert "_internal" in result  # Still present but marked internal

    @pytest.mark.parametrize("step_name,step_config,scope,expected_valid_scopes", [
        ("chunk_step", {}, "chunk", True),
        ("expr_step", {"expressions": {"x": "1"}}, "expression", True),
        ("fanout_step", {}, "fan_out", True),
        ("run_step", {}, "run", True),
        ("bad_step", {}, "invalid_scope", False),
    ])
    def test_validate_config_scope_validation(self, step_name, step_config, scope, expected_valid_scopes):
        """
        [Req: formal — config_validator.py] Valid scopes: chunk, run, expression, fan_out.
        """
        step = {"name": step_name, "scope": scope}
        step.update(step_config)
        config = {"pipeline": {"steps": [step]}, "processing": {"strategy": "direct", "items": {"source": "items.yaml"}}}
        errors = validate_config(config)
        if expected_valid_scopes:
            assert not any("invalid scope" in e.lower() for e in errors), (
                f"Scope '{scope}' should be valid but got error: {errors}"
            )
        else:
            assert any("scope" in e.lower() or "invalid" in e.lower() for e in errors), (
                f"Scope '{scope}' should be invalid but no error: {errors}"
            )

    def test_verify_run_detects_duplicated_units(self, tmp_path):
        """
        [Req: inferred — from _verify_step() valid_count_with_dupes tracking]
        verify_run() detects when the same unit_id appears multiple times
        in validated output (duplicate API submissions).
        """
        run_dir = tmp_path / "run"
        make_run(run_dir, ["generate"], ["u1", "u2"])

        # Inject duplicate: u1 appears twice
        chunk_dir = run_dir / "chunks" / "chunk_000"
        write_jsonl(chunk_dir / "generate_validated.jsonl", [
            {"unit_id": "u1"}, {"unit_id": "u1"}, {"unit_id": "u2"}
        ])

        result = verify_run(run_dir)
        step_result = result["steps"][0]
        assert step_result["duplicated"] >= 1, "Duplicate unit_ids must be detected"

    def test_verify_run_detects_orphaned_units(self, tmp_path):
        """
        [Req: inferred — from _verify_step() orphaned_ids computation]
        verify_run() detects units in output that weren't in the expected set.
        """
        run_dir = tmp_path / "run"
        make_run(run_dir, ["generate"], ["u1", "u2"])

        # Inject orphan: u99 appeared from nowhere
        chunk_dir = run_dir / "chunks" / "chunk_000"
        write_jsonl(chunk_dir / "generate_validated.jsonl", [
            {"unit_id": "u1"}, {"unit_id": "u2"}, {"unit_id": "u99_orphan"}
        ])

        result = verify_run(run_dir)
        step_result = result["steps"][0]
        assert step_result["orphaned"] >= 1, "Orphaned unit_ids must be detected"

    def test_parse_duration_handles_combined_format(self):
        """
        [Req: inferred — from parse_duration() regex pattern]
        parse_duration handles combined h+m format like '1h30m'.
        """
        result = parse_duration("1h30m")
        assert result == 5400  # 90 minutes

    def test_count_step_units_returns_zero_for_missing_dir(self, tmp_path):
        """
        [Req: inferred — from count_step_units() chunks_dir.exists() guard]
        count_step_units on a run with no chunks directory returns zeros gracefully.
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        # count_step_units requires (run_dir, step_name, pipeline)
        result = count_step_units(run_dir, "generate", ["generate"])
        assert result == {"valid": 0, "failed": 0, "retry_pending": 0}

    def test_seeded_random_choice_uses_rng_not_global(self):
        """
        [Req: inferred — from SeededRandom class isolation design]
        SeededRandom uses its own _rng instance, not the global random module.
        Two SeededRandom instances with different seeds must produce different
        sequences even if called simultaneously.
        """
        rng_a = SeededRandom(100)
        rng_b = SeededRandom(200)
        seq_a = [rng_a.choice([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) for _ in range(20)]
        seq_b = [rng_b.choice([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) for _ in range(20)]
        assert seq_a != seq_b, "Different seeds must produce different sequences"

    def test_bug5_rate_limit_backoff_constants_exist(self):
        """
        [Req: formal — BUG-5] Exponential backoff schedule and auto-pause threshold
        must be defined as constants for rate-limited batch submissions.
        """
        assert hasattr(orchestrate, "RATE_LIMIT_BACKOFF_SCHEDULE"), (
            "BUG-5: RATE_LIMIT_BACKOFF_SCHEDULE constant must exist"
        )
        assert hasattr(orchestrate, "RATE_LIMIT_MAX_CONSECUTIVE"), (
            "BUG-5: RATE_LIMIT_MAX_CONSECUTIVE constant must exist"
        )
        schedule = orchestrate.RATE_LIMIT_BACKOFF_SCHEDULE
        assert len(schedule) >= 4, "Backoff schedule must have at least 4 entries"
        assert schedule == sorted(schedule), "Backoff schedule must be monotonically increasing"
        assert schedule[-1] <= 300, "Backoff cap must not exceed 300s"
        assert orchestrate.RATE_LIMIT_MAX_CONSECUTIVE == 5, "Auto-pause after 5 consecutive 429s"

    def test_bug8_watch_loop_calls_mark_run_complete_on_terminal(self):
        """
        [Req: formal — BUG-8] The watch loop must call mark_run_complete()
        when all chunks reach terminal state, and must also call
        mark_failed_chunks_without_retryable_failures_terminal() each tick
        to patch stuck FAILED chunks.
        """
        import inspect
        source = inspect.getsource(orchestrate._watch_loop)
        assert "mark_run_complete" in source, (
            "BUG-8: _watch_loop must call mark_run_complete() when run is terminal"
        )
        assert "mark_failed_chunks_without_retryable_failures_terminal" in source, (
            "BUG-8: _watch_loop must patch stuck FAILED chunks each tick"
        )

    def test_sigint_save_timeout_is_reasonable(self):
        """
        [Req: inferred — from SIGINT_SAVE_TIMEOUT = 5 constant]
        SIGINT save timeout must be bounded to prevent hanging on signal.
        """
        assert SIGINT_SAVE_TIMEOUT > 0, "SIGINT_SAVE_TIMEOUT must be positive"
        assert SIGINT_SAVE_TIMEOUT <= 10, (
            "SIGINT_SAVE_TIMEOUT should be <= 10s to ensure responsive shutdown"
        )

    def test_categorize_step_failures_empty_run_returns_empty(self, tmp_path):
        """
        [Req: inferred — from categorize_step_failures() chunks_dir guard]
        categorize_step_failures on a run with no chunks returns empty result.
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        result = categorize_step_failures(run_dir, "generate")
        assert "validation" in result
        assert "hard" in result

    def test_retry_validation_failures_skips_expression_steps(self, tmp_path):
        """
        [Req: formal — CLAUDE.md] Expression steps are deterministic — retrying
        the same math on the same input produces the same result. They must not
        be included in retry chunks.
        """
        run_dir = tmp_path / "run"
        run_dir.mkdir()
        (run_dir / "RUN_LOG.txt").write_text("")
        (run_dir / "config").mkdir()
        # Expression step in config
        config_yaml = (
            "pipeline:\n"
            "  steps:\n"
            "    - name: verify_hand\n"
            "      scope: expression\n"
            "      expressions:\n"
            "        result: 'True'\n"
            "processing:\n"
            "  strategy: direct\n"
            "  items:\n"
            "    source: items.yaml\n"
        )
        (run_dir / "config" / "config.yaml").write_text(config_yaml)

        chunk_dir = run_dir / "chunks" / "chunk_000"
        chunk_dir.mkdir(parents=True)
        write_jsonl(chunk_dir / "units.jsonl", [{"unit_id": "u1"}])
        write_jsonl(chunk_dir / "verify_hand_failures.jsonl", [
            {"unit_id": "u1", "failure_stage": "validation", "errors": ["failed"], "retry_count": 0}
        ])

        manifest = {
            "config": "config/config.yaml",
            "pipeline": ["verify_hand"],
            "chunks": {"chunk_000": {"state": "FAILED", "retries": 0, "items": 1}},
            "metadata": {},
        }
        write_manifest(run_dir, manifest)
        loaded = json.loads((run_dir / "MANIFEST.json").read_text())

        log_file = run_dir / "RUN_LOG.txt"
        count = retry_validation_failures(run_dir, loaded, log_file, max_retries=3)

        # Expression steps should produce 0 retry units (deterministic — retrying won't help)
        chunks_dir = run_dir / "chunks"
        retry_dirs = [d for d in chunks_dir.iterdir() if d.name.startswith("retry_")]
        assert len(retry_dirs) == 0, (
            "Expression step validation failures must NOT be retried — they are deterministic"
        )
